AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  NestLambdalith:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nest-lambdalith
      Runtime: nodejs22.x
      Handler: dist/main.handler
      CodeUri: roadmap/
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LocalApiUrl:
    Value: http://localhost:4566/_aws/execute-api/${ServerlessRestApi}/Prod/
